### ISSUE TITLE
Reproducing the experiment

### ISSUE THREAD

**Issue by ghoshsdeeep** [btsmart/bootstrapping-label-noise#2]
Whch file do I need to run to reproduce the experiments?

**Comment by btsmart** [comment]
The experiments were run using the `run_ablations.py` file. Here is the information from the README:

-----

### Reproducing Results

The main experiments in our paper can be reproduced by running `python run_ablations.py <experiment_name> <gpu_id>`. See `run_ablations.py` for a list of experiments that can be run.

We have attempted to seed our experiments, however we note that differences in hardware may lead to different results. We ran our experiments on machines using RTX 2080Tis and RTX 3090s.

-----

For example, you should hopefully be able to reproduce our results on Animal10N by running `python run_ablations.py animal10n 0`. If you are getting errors when trying to run this, you may first need to run `python run_ablations.py setup_animal10n_datasets 0`. See the README for more info.

**Comment by ghoshsdeeep** [comment]
Thank you so much.Just one more help.Can you tell me which file contains the augmentations for test data

**Comment by btsmart** [comment]
Each dataset has its own file with its own augmentations. For example, the augmentations for Cifar10 are in `/datasets/cifar10/cifar10.py` under the augmentations heading. The augmentations will typically have a variable name ending in `_transform`
