### ISSUE TITLE
IndexError in DataLoader worker process 0

### ISSUE THREAD

**Issue by ghoshsdeeep** [btsmart/bootstrapping-label-noise#3]
Hi Brandon
This is Subhadeep ,I have been trying to implement your repo
I have been running the code using CIFAR100.However it seems I am getting an empty noise distribution array. Any idea how I might be able to fix this issue? I d be grateful for any assistance

![Screenshot (110)](https://github.com/btsmart/bootstrapping-label-noise/assets/12712069/edd50aff-84e9-4919-8a6b-d97ba209cd4a)
![Screenshot (111)](https://github.com/btsmart/bootstrapping-label-noise/assets/12712069/65844d85-0a1e-4369-aadd-6af6943b4dbc)
![Screenshot (112)](https://github.com/btsmart/bootstrapping-label-noise/assets/12712069/b3381a40-e614-4c9b-9509-ed5840800c6a)

**Comment by ghoshsdeeep** [comment]
![Screenshot (113)](https://github.com/btsmart/bootstrapping-label-noise/assets/12712069/36022158-4f53-4f89-92d2-04f9ac7ac188)

**Comment by btsmart** [comment]
Hello Subhadeep,

I think I have been able to recreate your issue. The datasets from the Google Drive link were correct, but there was an issue with the implementation of `DS.save_to_file` in `datasets/dataset.py` which meant that newly generated datasets (such as from `python run_ablations setup_cifar100_datasets 0`) had incorrectly saved 'null' values that should have been skipped.

I have updated `datasets/dataset.py` which should hopefully fix the issue. Alternatively, you can download and use the datasets from the Google Drive link mentioned in the README. I haven't had much of a chance to test my new changes, so please let me know if the issue persists, or if you run into any new issues.
